- name: "Fast Track Small PRs"
  conditions:
      - type: "lines_changed"
        operator: "<="
        value: 50
  actions:
      - type: "auto_merge"
- name: "High-Risk Code Review"
  conditions:
      - type: "files"
        pattern: "src/security/**"
  actions:
      - type: "request_review"
  reviewers:
      - "security-team"
